// -----------------------------------------------------------------------
// This is generated code, do not edit unless you know what you are doing!
// -----------------------------------------------------------------------

#ifndef SDKCONFIG_a768af09a3b0402b8b950d51cf5182f8
#define SDKCONFIG_a768af09a3b0402b8b950d51cf5182f8

// menuconfig uses y and n macros for boolean values
// we need to assign values to them to be able to do
// #if checks
#ifndef y
#define y 1
#endif // y

#ifndef n
#define n 0
#endif // n

//
// Presence Cube
//
//
// Web Server
//
// CONFIG_WEBSERVER_ENABLED is not set
// end of Web Server
//
// Light Control
//
//
// RGBA East
//
#ifndef CONFIG_RGBA_EAST_RED_CHANNEL_PIN
#define CONFIG_RGBA_EAST_RED_CHANNEL_PIN 14
#endif // CONFIG_RGBA_EAST_RED_CHANNEL_PIN

#ifndef CONFIG_RGBA_EAST_GREEN_CHANNEL_PIN
#define CONFIG_RGBA_EAST_GREEN_CHANNEL_PIN 14
#endif // CONFIG_RGBA_EAST_GREEN_CHANNEL_PIN

#ifndef CONFIG_RGBA_EAST_BLUE_CHANNEL_PIN
#define CONFIG_RGBA_EAST_BLUE_CHANNEL_PIN 15
#endif // CONFIG_RGBA_EAST_BLUE_CHANNEL_PIN

// end of RGBA East
//
// RGBA West
//
#ifndef CONFIG_RGBA_WEST_RED_CHANNEL_PIN
#define CONFIG_RGBA_WEST_RED_CHANNEL_PIN 23
#endif // CONFIG_RGBA_WEST_RED_CHANNEL_PIN

#ifndef CONFIG_RGBA_WEST_GREEN_CHANNEL_PIN
#define CONFIG_RGBA_WEST_GREEN_CHANNEL_PIN 32
#endif // CONFIG_RGBA_WEST_GREEN_CHANNEL_PIN

#ifndef CONFIG_RGBA_WEST_BLUE_CHANNEL_PIN
#define CONFIG_RGBA_WEST_BLUE_CHANNEL_PIN 33
#endif // CONFIG_RGBA_WEST_BLUE_CHANNEL_PIN

// end of RGBA West
#ifndef CONFIG_PWM_FADE_INTERVAL
#define CONFIG_PWM_FADE_INTERVAL 3000
#endif // CONFIG_PWM_FADE_INTERVAL

// end of Light Control
//
// Hardware Characteristics
//
#ifndef CONFIG_CUBE_HARDWARE_RGB_LED_COUNT
#define CONFIG_CUBE_HARDWARE_RGB_LED_COUNT 0
#endif // CONFIG_CUBE_HARDWARE_RGB_LED_COUNT

#ifndef CONFIG_HARDWARE_RGB_LED_TYPE_COMMON_ANODE
#define CONFIG_HARDWARE_RGB_LED_TYPE_COMMON_ANODE y
#endif // CONFIG_HARDWARE_RGB_LED_TYPE_COMMON_ANODE

// CONFIG_HARDWARE_RGB_LED_TYPE_COMMON_CATHODE is not set
// end of Hardware Characteristics
//
// MQTT Settings
//
#ifndef CONFIG_ESP_MQTT_BROKER_URI
#define CONFIG_ESP_MQTT_BROKER_URI "mqtt://broker.hivemq.com:1883/z-hydrobay01/control"
#endif // CONFIG_ESP_MQTT_BROKER_URI

#ifndef CONFIG_ESP_MQTT_BROKER_USER
#define CONFIG_ESP_MQTT_BROKER_USER "username"
#endif // CONFIG_ESP_MQTT_BROKER_USER

#ifndef CONFIG_ESP_MQTT_BROKER_PASSWORD
#define CONFIG_ESP_MQTT_BROKER_PASSWORD "password"
#endif // CONFIG_ESP_MQTT_BROKER_PASSWORD

#ifndef CONFIG_ESP_MQTT_DATA_TOPIC
#define CONFIG_ESP_MQTT_DATA_TOPIC "data"
#endif // CONFIG_ESP_MQTT_DATA_TOPIC

#ifndef CONFIG_ESP_MQTT_CONTROL_TOPIC
#define CONFIG_ESP_MQTT_CONTROL_TOPIC "control"
#endif // CONFIG_ESP_MQTT_CONTROL_TOPIC

// end of MQTT Settings
// end of Presence Cube
//
// Wifi Credentials
//
#ifndef CONFIG_WIFI_SSID
#define CONFIG_WIFI_SSID "myssid"
#endif // CONFIG_WIFI_SSID

#ifndef CONFIG_WIFI_PASSWORD
#define CONFIG_WIFI_PASSWORD "mypasswordd"
#endif // CONFIG_WIFI_PASSWORD

// end of Wifi Credentials
//
// Hardware Agnostic Graphics Library HAL (MIPI)
//
//
// Display orientation
//
// CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_Y_SELECTED is not set
// CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_X_SELECTED is not set
// CONFIG_MIPI_DCS_ADDRESS_MODE_SWAP_XY_SELECTED is not set
// CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_X_SELECTED is not set
// CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_Y_SELECTED is not set
// end of Display orientation
#ifndef CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_Y
#define CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_Y 0x00
#endif // CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_Y

#ifndef CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_X
#define CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_X 0x00
#endif // CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_X

#ifndef CONFIG_MIPI_DCS_ADDRESS_MODE_SWAP_XY
#define CONFIG_MIPI_DCS_ADDRESS_MODE_SWAP_XY 0x00
#endif // CONFIG_MIPI_DCS_ADDRESS_MODE_SWAP_XY

#ifndef CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_X
#define CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_X 0x00
#endif // CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_X

#ifndef CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_Y
#define CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_Y 0x00
#endif // CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_Y

// CONFIG_MIPI_DCS_PIXEL_FORMAT_24BIT_SELECTED is not set
// CONFIG_MIPI_DCS_PIXEL_FORMAT_18BIT_SELECTED is not set
#ifndef CONFIG_MIPI_DCS_PIXEL_FORMAT_16BIT_SELECTED
#define CONFIG_MIPI_DCS_PIXEL_FORMAT_16BIT_SELECTED y
#endif // CONFIG_MIPI_DCS_PIXEL_FORMAT_16BIT_SELECTED

// CONFIG_MIPI_DCS_PIXEL_FORMAT_12BIT_SELECTED is not set
// CONFIG_MIPI_DCS_PIXEL_FORMAT_8BIT_SELECTED is not set
// CONFIG_MIPI_DCS_PIXEL_FORMAT_3BIT_SELECTED is not set
#ifndef CONFIG_MIPI_DISPLAY_PIXEL_FORMAT
#define CONFIG_MIPI_DISPLAY_PIXEL_FORMAT 0x55
#endif // CONFIG_MIPI_DISPLAY_PIXEL_FORMAT

#ifndef CONFIG_MIPI_DISPLAY_DEPTH
#define CONFIG_MIPI_DISPLAY_DEPTH 16
#endif // CONFIG_MIPI_DISPLAY_DEPTH

#ifndef CONFIG_HAGL_HAL_NO_BUFFERING
#define CONFIG_HAGL_HAL_NO_BUFFERING y
#endif // CONFIG_HAGL_HAL_NO_BUFFERING

// CONFIG_HAGL_HAL_USE_DOUBLE_BUFFERING is not set
// CONFIG_HAGL_HAL_USE_TRIPLE_BUFFERING is not set
#ifndef CONFIG_MIPI_DISPLAY_WIDTH
#define CONFIG_MIPI_DISPLAY_WIDTH 320
#endif // CONFIG_MIPI_DISPLAY_WIDTH

#ifndef CONFIG_MIPI_DISPLAY_HEIGHT
#define CONFIG_MIPI_DISPLAY_HEIGHT 240
#endif // CONFIG_MIPI_DISPLAY_HEIGHT

#ifndef CONFIG_MIPI_DISPLAY_OFFSET_X
#define CONFIG_MIPI_DISPLAY_OFFSET_X 0
#endif // CONFIG_MIPI_DISPLAY_OFFSET_X

#ifndef CONFIG_MIPI_DISPLAY_OFFSET_Y
#define CONFIG_MIPI_DISPLAY_OFFSET_Y 0
#endif // CONFIG_MIPI_DISPLAY_OFFSET_Y

// CONFIG_MIPI_DISPLAY_INVERT is not set
// CONFIG_MIPI_DCS_ADDRESS_MODE_BGR_SELECTED is not set
#ifndef CONFIG_MIPI_DCS_ADDRESS_MODE_BGR
#define CONFIG_MIPI_DCS_ADDRESS_MODE_BGR 0x00
#endif // CONFIG_MIPI_DCS_ADDRESS_MODE_BGR

#ifndef CONFIG_MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ
#define CONFIG_MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ 40000000
#endif // CONFIG_MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ

#ifndef CONFIG_MIPI_DISPLAY_SPI_MODE
#define CONFIG_MIPI_DISPLAY_SPI_MODE 0
#endif // CONFIG_MIPI_DISPLAY_SPI_MODE

#ifndef CONFIG_MIPI_DISPLAY_PIN_MISO
#define CONFIG_MIPI_DISPLAY_PIN_MISO -1
#endif // CONFIG_MIPI_DISPLAY_PIN_MISO

#ifndef CONFIG_MIPI_DISPLAY_PIN_MOSI
#define CONFIG_MIPI_DISPLAY_PIN_MOSI 23
#endif // CONFIG_MIPI_DISPLAY_PIN_MOSI

#ifndef CONFIG_MIPI_DISPLAY_PIN_CLK
#define CONFIG_MIPI_DISPLAY_PIN_CLK 18
#endif // CONFIG_MIPI_DISPLAY_PIN_CLK

#ifndef CONFIG_MIPI_DISPLAY_PIN_CS
#define CONFIG_MIPI_DISPLAY_PIN_CS 14
#endif // CONFIG_MIPI_DISPLAY_PIN_CS

#ifndef CONFIG_MIPI_DISPLAY_PIN_DC
#define CONFIG_MIPI_DISPLAY_PIN_DC 27
#endif // CONFIG_MIPI_DISPLAY_PIN_DC

#ifndef CONFIG_MIPI_DISPLAY_PIN_RST
#define CONFIG_MIPI_DISPLAY_PIN_RST 33
#endif // CONFIG_MIPI_DISPLAY_PIN_RST

#ifndef CONFIG_MIPI_DISPLAY_PIN_BL
#define CONFIG_MIPI_DISPLAY_PIN_BL 32
#endif // CONFIG_MIPI_DISPLAY_PIN_BL

#ifndef CONFIG_MIPI_DISPLAY_PWM_BL
#define CONFIG_MIPI_DISPLAY_PWM_BL -1
#endif // CONFIG_MIPI_DISPLAY_PWM_BL

// end of Hardware Agnostic Graphics Library HAL (MIPI)
//
// Hardware Agnostic Graphics Library (HAGL)
//
#ifndef CONFIG_HAGL_TJPGD_NEEDS_BYTESWAP
#define CONFIG_HAGL_TJPGD_NEEDS_BYTESWAP y
#endif // CONFIG_HAGL_TJPGD_NEEDS_BYTESWAP

// end of Hardware Agnostic Graphics Library (HAGL)
#endif // SDKCONFIG_a768af09a3b0402b8b950d51cf5182f8

