# Learn more: 
# https://docs.gitlab.com/ee/ci/yaml/README.html#script
# https://docs.platformio.org/en/latest/integration/ci/gitlab.html
# https://electric-toast.com/esp32-diy-smarter-home-collect-measurements/
# https://www.reddit.com/r/esp32/comments/est2wj/full_platformio_cicd/

# After committing this template, visit CI/CD > Jobs to see the script output.

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_STRATEGY: default
  PLATFORMIO_CI_SRC: src/main.c
  PLATFORMIO_PIP_VERSION: '6.1.3'
  FLAWFINDER_PIP_VERSION: '2.0.19'
  PYTHON_DOCKER_VERSION: '3.8'

image: python:$PYTHON_DOCKER_VERSION

before_script:
  - 'echo "----------- Variables ---------------"'
  - 'echo "CI_JOB_STAGE: $CI_JOB_STAGE"'
  - 'echo "CI_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME"'
  - 'echo "PWD: $PWD"'
  - 'echo'

# list:
#   stage: build
#   script:
#     # Listing all environment variables is a security risk! Use with caution!
#     # https://docs.gitlab.com/ee/ci/variables/index.html#list-all-environment-variables
#     - export

build:
 stage: build
 image: python:$PYTHON_DOCKER_VERSION
 allow_failure: false
 interruptible: true
 script: 
   - "pip install -U platformio==$PLATFORMIO_PIP_VERSION"
   - "./build_env.sh --environment native-dev"

tests:
 stage: test
 image: python:$PYTHON_DOCKER_VERSION
 allow_failure: false
 interruptible: true
 script:
   - "pip install -U platformio==$PLATFORMIO_PIP_VERSION"
   - "./test_native.sh"

    
gitstats:
  stage: build
  image: masaedw/gitstats
  allow_failure: true
  interruptible: true
  script:
    - gitstats . gitstats.html
  artifacts:
    paths:
      - gitstats.html
  only:
      - master

flawfinder:
  stage: test
  image: python:$PYTHON_DOCKER_VERSION
  allow_failure: true
  interruptible: true
  script: 
    - python -m pip install flawfinder==$FLAWFINDER_PIP_VERSION
    - flawfinder --context --html ./src ./test > flawfinder.html
  artifacts:
    paths:
      - flawfinder.html
