name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install PlatformIO
        run: |
          apt update && apt install -y pipx build-essential
          pipx install platformio==6.1.14
          pipx ensurepath
      - name: Build Native
        run: $HOME/.local/bin/pio run --environment native-dev
      - name: Build Embedded
        run: $HOME/.local/bin/pio run --environment espressif32-dev